# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_about.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AWindow(object):
    def setupUi(self, AWindow):
        AWindow.setObjectName("AWindow")
        AWindow.resize(570, 400)
        AWindow.setMinimumSize(QtCore.QSize(570, 400))
        AWindow.setMaximumSize(QtCore.QSize(570, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(AWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.header_old = QtWidgets.QLabel(self.centralwidget)
        self.header_old.setGeometry(QtCore.QRect(50, 30, 471, 41))
        font = QtGui.QFont()
        font.setFamily("Titr")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.header_old.setFont(font)
        self.header_old.setObjectName("header_old")
        self.header_old_2 = QtWidgets.QLabel(self.centralwidget)
        self.header_old_2.setGeometry(QtCore.QRect(230, 70, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.header_old_2.setFont(font)
        self.header_old_2.setObjectName("header_old_2")
        self.header_old_3 = QtWidgets.QLabel(self.centralwidget)
        self.header_old_3.setGeometry(QtCore.QRect(120, 110, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.header_old_3.setFont(font)
        self.header_old_3.setObjectName("header_old_3")
        self.header_old_4 = QtWidgets.QLabel(self.centralwidget)
        self.header_old_4.setGeometry(QtCore.QRect(90, 180, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.header_old_4.setFont(font)
        self.header_old_4.setObjectName("header_old_4")
        self.header_old_5 = QtWidgets.QLabel(self.centralwidget)
        self.header_old_5.setGeometry(QtCore.QRect(260, 180, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.header_old_5.setFont(font)
        self.header_old_5.setObjectName("header_old_5")
        self.header_old_6 = QtWidgets.QLabel(self.centralwidget)
        self.header_old_6.setGeometry(QtCore.QRect(300, 250, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.header_old_6.setFont(font)
        self.header_old_6.setObjectName("header_old_6")
        self.header_old_7 = QtWidgets.QLabel(self.centralwidget)
        self.header_old_7.setGeometry(QtCore.QRect(90, 320, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.header_old_7.setFont(font)
        self.header_old_7.setObjectName("header_old_7")
        self.header_old_8 = QtWidgets.QLabel(self.centralwidget)
        self.header_old_8.setGeometry(QtCore.QRect(260, 320, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.header_old_8.setFont(font)
        self.header_old_8.setObjectName("header_old_8")
        self.header_old_9 = QtWidgets.QLabel(self.centralwidget)
        self.header_old_9.setGeometry(QtCore.QRect(90, 250, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.header_old_9.setFont(font)
        self.header_old_9.setObjectName("header_old_9")
        AWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AWindow)
        self.statusbar.setObjectName("statusbar")
        AWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AWindow)
        QtCore.QMetaObject.connectSlotsByName(AWindow)

    def retranslateUi(self, AWindow):
        _translate = QtCore.QCoreApplication.translate
        AWindow.setWindowTitle(_translate("AWindow", "درباره ما"))
        self.header_old.setText(_translate("AWindow", "IstaSanat Online Voting System"))
        self.header_old_2.setText(_translate("AWindow", "Ver 1.0.0"))
        self.header_old_3.setText(_translate("AWindow", "CopyRight (C) 2018 The IstaSanat Co."))
        self.header_old_4.setText(_translate("AWindow", "Designer:"))
        self.header_old_5.setText(_translate("AWindow", "Hosein Alam Shahi"))
        self.header_old_6.setText(_translate("AWindow", "Sina Shiri"))
        self.header_old_7.setText(_translate("AWindow", "Contact Us:"))
        self.header_old_8.setText(_translate("AWindow", "+98914-400-22-64"))
        self.header_old_9.setText(_translate("AWindow", "Programmer:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AWindow = QtWidgets.QMainWindow()
    ui = Ui_AWindow()
    ui.setupUi(AWindow)
    AWindow.show()
    sys.exit(app.exec_())

