# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_add_new.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NWindow(object):
    def setupUi(self, NWindow):
        NWindow.setObjectName("NWindow")
        NWindow.resize(570, 316)
        NWindow.setMinimumSize(QtCore.QSize(570, 316))
        NWindow.setMaximumSize(QtCore.QSize(570, 316))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("online.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(NWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(440, 50, 101, 31))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.header_new = QtWidgets.QLabel(self.centralwidget)
        self.header_new.setGeometry(QtCore.QRect(390, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.header_new.setFont(font)
        self.header_new.setObjectName("header_new")
        self.Question = QtWidgets.QLineEdit(self.centralwidget)
        self.Question.setGeometry(QtCore.QRect(12, 80, 531, 31))
        font = QtGui.QFont()
        font.setFamily("B Lotus")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Question.setFont(font)
        self.Question.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Question.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Question.setObjectName("Question")
        self.Choice_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.Choice_1.setGeometry(QtCore.QRect(402, 140, 141, 31))
        font = QtGui.QFont()
        font.setFamily("B Lotus")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Choice_1.setFont(font)
        self.Choice_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Choice_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Choice_1.setObjectName("Choice_1")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(440, 110, 101, 31))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Choice_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.Choice_2.setGeometry(QtCore.QRect(230, 140, 141, 31))
        font = QtGui.QFont()
        font.setFamily("B Lotus")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Choice_2.setFont(font)
        self.Choice_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Choice_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Choice_2.setObjectName("Choice_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(440, 180, 101, 31))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.Choice_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.Choice_3.setGeometry(QtCore.QRect(60, 140, 141, 31))
        font = QtGui.QFont()
        font.setFamily("B Lotus")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Choice_3.setFont(font)
        self.Choice_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Choice_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Choice_3.setObjectName("Choice_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(270, 110, 101, 31))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.Choice_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.Choice_4.setGeometry(QtCore.QRect(400, 210, 141, 31))
        font = QtGui.QFont()
        font.setFamily("B Lotus")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Choice_4.setFont(font)
        self.Choice_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Choice_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Choice_4.setObjectName("Choice_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(270, 180, 101, 31))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.Choice_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.Choice_5.setGeometry(QtCore.QRect(230, 210, 141, 31))
        font = QtGui.QFont()
        font.setFamily("B Lotus")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Choice_5.setFont(font)
        self.Choice_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Choice_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Choice_5.setObjectName("Choice_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(98, 110, 101, 31))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.ok_button = QtWidgets.QPushButton(self.centralwidget)
        self.ok_button.setGeometry(QtCore.QRect(20, 250, 93, 28))
        font = QtGui.QFont()
        font.setFamily("B Lotus")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ok_button.setFont(font)
        self.ok_button.setObjectName("ok_button")
        self.cancel_button = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_button.setGeometry(QtCore.QRect(120, 250, 93, 28))
        font = QtGui.QFont()
        font.setFamily("B Lotus")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_button.setFont(font)
        self.cancel_button.setObjectName("cancel_button")
        NWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(NWindow)
        self.statusbar.setObjectName("statusbar")
        NWindow.setStatusBar(self.statusbar)

        self.retranslateUi(NWindow)
        QtCore.QMetaObject.connectSlotsByName(NWindow)

    def retranslateUi(self, NWindow):
        _translate = QtCore.QCoreApplication.translate
        NWindow.setWindowTitle(_translate("NWindow", "افزودن نظرسنجی جدید"))
        self.label.setText(_translate("NWindow", "سوال:"))
        self.header_new.setText(_translate("NWindow", "ایجاد نظرسنجی جدید"))
        self.label_3.setText(_translate("NWindow", "گزینه یک:"))
        self.label_4.setText(_translate("NWindow", "گزینه چهار:"))
        self.label_5.setText(_translate("NWindow", "گزینه دو:"))
        self.label_6.setText(_translate("NWindow", "گزینه پنج:"))
        self.label_7.setText(_translate("NWindow", "گزینه سه:"))
        self.ok_button.setText(_translate("NWindow", "تایید"))
        self.cancel_button.setText(_translate("NWindow", "انصراف"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NWindow = QtWidgets.QMainWindow()
    ui = Ui_NWindow()
    ui.setupUi(NWindow)
    NWindow.show()
    sys.exit(app.exec_())

