# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_basic.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("online.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LCD_NUM_5 = QtWidgets.QLCDNumber(self.centralwidget)
        self.LCD_NUM_5.setGeometry(QtCore.QRect(910, 710, 101, 51))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.LCD_NUM_5.setFont(font)
        self.LCD_NUM_5.setDigitCount(6)
        self.LCD_NUM_5.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.LCD_NUM_5.setObjectName("LCD_NUM_5")
        self.refresh_button = QtWidgets.QPushButton(self.centralwidget)
        self.refresh_button.setGeometry(QtCore.QRect(610, 510, 101, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.refresh_button.setFont(font)
        self.refresh_button.setObjectName("refresh_button")
        self.LCD_NUM_4 = QtWidgets.QLCDNumber(self.centralwidget)
        self.LCD_NUM_4.setGeometry(QtCore.QRect(800, 710, 101, 51))
        self.LCD_NUM_4.setDigitCount(6)
        self.LCD_NUM_4.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.LCD_NUM_4.setObjectName("LCD_NUM_4")
        self.LCD_NUM_3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.LCD_NUM_3.setGeometry(QtCore.QRect(690, 710, 101, 51))
        self.LCD_NUM_3.setDigitCount(6)
        self.LCD_NUM_3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.LCD_NUM_3.setObjectName("LCD_NUM_3")
        self.LCD_NUM_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.LCD_NUM_2.setGeometry(QtCore.QRect(580, 710, 101, 51))
        self.LCD_NUM_2.setDigitCount(6)
        self.LCD_NUM_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.LCD_NUM_2.setObjectName("LCD_NUM_2")
        self.LCD_NUM_1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.LCD_NUM_1.setGeometry(QtCore.QRect(470, 710, 101, 51))
        self.LCD_NUM_1.setDigitCount(6)
        self.LCD_NUM_1.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.LCD_NUM_1.setObjectName("LCD_NUM_1")
        self.LCD_NUM_TOTAL = QtWidgets.QLCDNumber(self.centralwidget)
        self.LCD_NUM_TOTAL.setGeometry(QtCore.QRect(330, 700, 131, 61))
        self.LCD_NUM_TOTAL.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.LCD_NUM_TOTAL.setSmallDecimalPoint(False)
        self.LCD_NUM_TOTAL.setDigitCount(7)
        self.LCD_NUM_TOTAL.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.LCD_NUM_TOTAL.setObjectName("LCD_NUM_TOTAL")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 660, 101, 31))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(470, 670, 101, 31))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(580, 670, 101, 31))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(690, 670, 101, 31))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(800, 670, 101, 31))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(910, 670, 101, 31))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(570, 140, 441, 361))
        self.graphicsView.setAutoFillBackground(False)
        self.graphicsView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.graphicsView.setObjectName("graphicsView")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(954, 510, 51, 41))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(720, 510, 221, 41))
        font = QtGui.QFont()
        font.setFamily("B Zar")
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.comboBox.setObjectName("comboBox")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(420, 30, 41, 31))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(800, 30, 41, 31))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(710, 30, 41, 31))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(850, 30, 61, 31))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(620, 30, 41, 31))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(530, 30, 41, 31))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 140, 551, 361))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.zoom_button = QtWidgets.QPushButton(self.centralwidget)
        self.zoom_button.setGeometry(QtCore.QRect(870, 100, 141, 31))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(10)
        self.zoom_button.setFont(font)
        self.zoom_button.setObjectName("zoom_button")
        self.rpi_mode_1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.rpi_mode_1.setGeometry(QtCore.QRect(760, 20, 51, 51))
        self.rpi_mode_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rpi_mode_1.setObjectName("rpi_mode_1")
        self.rpi_mode_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.rpi_mode_2.setGeometry(QtCore.QRect(670, 20, 51, 51))
        self.rpi_mode_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rpi_mode_2.setObjectName("rpi_mode_2")
        self.rpi_mode_3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.rpi_mode_3.setGeometry(QtCore.QRect(580, 20, 51, 51))
        self.rpi_mode_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rpi_mode_3.setObjectName("rpi_mode_3")
        self.rpi_mode_4 = QtWidgets.QGraphicsView(self.centralwidget)
        self.rpi_mode_4.setGeometry(QtCore.QRect(470, 20, 51, 51))
        self.rpi_mode_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rpi_mode_4.setObjectName("rpi_mode_4")
        self.rpi_mode_5 = QtWidgets.QGraphicsView(self.centralwidget)
        self.rpi_mode_5.setGeometry(QtCore.QRect(370, 20, 51, 51))
        self.rpi_mode_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rpi_mode_5.setObjectName("rpi_mode_5")
        self.plot = QtWidgets.QWidget(self.centralwidget)
        self.plot.setGeometry(QtCore.QRect(-60, 460, 481, 351))
        self.plot.setMaximumSize(QtCore.QSize(481, 16777215))
        self.plot.setObjectName("plot")
        self.new_vote = QtWidgets.QPushButton(self.centralwidget)
        self.new_vote.setGeometry(QtCore.QRect(20, 10, 131, 28))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.new_vote.setFont(font)
        self.new_vote.setObjectName("new_vote")
        self.old_vote = QtWidgets.QPushButton(self.centralwidget)
        self.old_vote.setGeometry(QtCore.QRect(20, 70, 131, 28))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.old_vote.setFont(font)
        self.old_vote.setObjectName("old_vote")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(890, 570, 111, 41))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.question = QtWidgets.QLabel(self.centralwidget)
        self.question.setGeometry(QtCore.QRect(430, 620, 571, 41))
        font = QtGui.QFont()
        font.setFamily("B Lotus")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.question.setFont(font)
        self.question.setText("")
        self.question.setObjectName("question")
        self.clients_ip = QtWidgets.QPushButton(self.centralwidget)
        self.clients_ip.setGeometry(QtCore.QRect(160, 10, 131, 28))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.clients_ip.setFont(font)
        self.clients_ip.setObjectName("clients_ip")
        self.about_us = QtWidgets.QPushButton(self.centralwidget)
        self.about_us.setGeometry(QtCore.QRect(90, 100, 131, 28))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.about_us.setFont(font)
        self.about_us.setObjectName("about_us")
        self.server_ip = QtWidgets.QPushButton(self.centralwidget)
        self.server_ip.setGeometry(QtCore.QRect(160, 40, 131, 28))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.server_ip.setFont(font)
        self.server_ip.setObjectName("server_ip")
        self.active_old_vote = QtWidgets.QPushButton(self.centralwidget)
        self.active_old_vote.setGeometry(QtCore.QRect(20, 40, 131, 28))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.active_old_vote.setFont(font)
        self.active_old_vote.setObjectName("active_old_vote")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(430, 510, 171, 81))
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.autoUpdatTime = QtWidgets.QTimeEdit(self.frame)
        self.autoUpdatTime.setGeometry(QtCore.QRect(50, 40, 61, 31))
        self.autoUpdatTime.setMinimumTime(QtCore.QTime(0, 0, 15))
        self.autoUpdatTime.setCurrentSection(QtWidgets.QDateTimeEdit.MinuteSection)
        self.autoUpdatTime.setObjectName("autoUpdatTime")
        self.autoUpdateCheckBox = QtWidgets.QCheckBox(self.frame)
        self.autoUpdateCheckBox.setGeometry(QtCore.QRect(0, 0, 161, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.autoUpdateCheckBox.setFont(font)
        self.autoUpdateCheckBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.autoUpdateCheckBox.setObjectName("autoUpdateCheckBox")
        self.report = QtWidgets.QPushButton(self.centralwidget)
        self.report.setGeometry(QtCore.QRect(160, 70, 131, 28))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.report.setFont(font)
        self.report.setObjectName("report")
        self.label_4.raise_()
        self.LCD_NUM_5.raise_()
        self.refresh_button.raise_()
        self.LCD_NUM_4.raise_()
        self.LCD_NUM_3.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.graphicsView.raise_()
        self.label_7.raise_()
        self.comboBox.raise_()
        self.label_13.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_8.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.zoom_button.raise_()
        self.rpi_mode_1.raise_()
        self.rpi_mode_2.raise_()
        self.rpi_mode_3.raise_()
        self.rpi_mode_4.raise_()
        self.rpi_mode_5.raise_()
        self.plot.raise_()
        self.tableWidget.raise_()
        self.LCD_NUM_1.raise_()
        self.LCD_NUM_TOTAL.raise_()
        self.label_3.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.LCD_NUM_2.raise_()
        self.new_vote.raise_()
        self.old_vote.raise_()
        self.label_14.raise_()
        self.question.raise_()
        self.clients_ip.raise_()
        self.about_us.raise_()
        self.server_ip.raise_()
        self.active_old_vote.raise_()
        self.frame.raise_()
        self.report.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ایستا صنعت"))
        self.refresh_button.setText(_translate("MainWindow", "به روزرسانی"))
        self.label.setText(_translate("MainWindow", "کـــل آرا"))
        self.label_2.setText(_translate("MainWindow", "گزینه یک"))
        self.label_3.setText(_translate("MainWindow", "گزینه دو"))
        self.label_4.setText(_translate("MainWindow", "گزینه سه"))
        self.label_5.setText(_translate("MainWindow", "گزینه چهار"))
        self.label_6.setText(_translate("MainWindow", "گزینه پنج"))
        self.label_7.setText(_translate("MainWindow", "آمار: "))
        self.label_13.setText(_translate("MainWindow", "پنج"))
        self.label_9.setText(_translate("MainWindow", "یک"))
        self.label_10.setText(_translate("MainWindow", "دو"))
        self.label_8.setText(_translate("MainWindow", "دستگاه :"))
        self.label_11.setText(_translate("MainWindow", "سه"))
        self.label_12.setText(_translate("MainWindow", "چهار"))
        self.zoom_button.setText(_translate("MainWindow", "بزرگنمایی تصویر"))
        self.new_vote.setText(_translate("MainWindow", "ایجاد نظرسنجی جدید"))
        self.old_vote.setText(_translate("MainWindow", "بارگذاری نظرسنجی"))
        self.label_14.setText(_translate("MainWindow", "نظرسنجی:"))
        self.clients_ip.setText(_translate("MainWindow", "تنظیمات دستگاه ها"))
        self.about_us.setText(_translate("MainWindow", "درباره مــــــا"))
        self.server_ip.setText(_translate("MainWindow", "تنظیمات سرور دیتابیس"))
        self.active_old_vote.setText(_translate("MainWindow", "انتخاب نظرسنجی فعال"))
        self.autoUpdatTime.setDisplayFormat(_translate("MainWindow", "mm:ss"))
        self.autoUpdateCheckBox.setText(_translate("MainWindow", "به روزرسانی اتوماتیک"))
        self.report.setText(_translate("MainWindow", "گزارش گیری"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

