# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ip.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_IWindow(object):
    def setupUi(self, IWindow):
        IWindow.setObjectName("IWindow")
        IWindow.resize(385, 393)
        IWindow.setMinimumSize(QtCore.QSize(385, 362))
        IWindow.setMaximumSize(QtCore.QSize(99999, 110000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("online.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        IWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(IWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.header_new = QtWidgets.QLabel(self.centralwidget)
        self.header_new.setGeometry(QtCore.QRect(40, 0, 341, 41))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.header_new.setFont(font)
        self.header_new.setObjectName("header_new")
        self.ip_device_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.ip_device_1.setGeometry(QtCore.QRect(20, 50, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ip_device_1.setFont(font)
        self.ip_device_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ip_device_1.setInputMask("")
        self.ip_device_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ip_device_1.setObjectName("ip_device_1")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 50, 171, 31))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.ip_device_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.ip_device_2.setGeometry(QtCore.QRect(20, 100, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ip_device_2.setFont(font)
        self.ip_device_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ip_device_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ip_device_2.setObjectName("ip_device_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(200, 200, 171, 31))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.ip_device_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.ip_device_3.setGeometry(QtCore.QRect(20, 150, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ip_device_3.setFont(font)
        self.ip_device_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ip_device_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ip_device_3.setObjectName("ip_device_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(210, 100, 161, 31))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.ip_device_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.ip_device_4.setGeometry(QtCore.QRect(20, 200, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ip_device_4.setFont(font)
        self.ip_device_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ip_device_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ip_device_4.setObjectName("ip_device_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(200, 250, 171, 31))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.ip_device_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.ip_device_5.setGeometry(QtCore.QRect(20, 250, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ip_device_5.setFont(font)
        self.ip_device_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ip_device_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ip_device_5.setObjectName("ip_device_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(200, 150, 171, 31))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.ok_ip_button = QtWidgets.QPushButton(self.centralwidget)
        self.ok_ip_button.setGeometry(QtCore.QRect(100, 300, 93, 28))
        font = QtGui.QFont()
        font.setFamily("B Lotus")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ok_ip_button.setFont(font)
        self.ok_ip_button.setObjectName("ok_ip_button")
        self.cancel_ip_button = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_ip_button.setGeometry(QtCore.QRect(200, 300, 93, 28))
        font = QtGui.QFont()
        font.setFamily("B Lotus")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_ip_button.setFont(font)
        self.cancel_ip_button.setObjectName("cancel_ip_button")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 340, 331, 31))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        IWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(IWindow)
        self.statusbar.setObjectName("statusbar")
        IWindow.setStatusBar(self.statusbar)

        self.retranslateUi(IWindow)
        QtCore.QMetaObject.connectSlotsByName(IWindow)

    def retranslateUi(self, IWindow):
        _translate = QtCore.QCoreApplication.translate
        IWindow.setWindowTitle(_translate("IWindow", "افزودن نظرسنجی جدید"))
        self.header_new.setText(_translate("IWindow", "آی پی هر یک از دستگاه ها در شبکه محلی را وارد نمایید:"))
        self.label_3.setText(_translate("IWindow", "آی پی دستگاه شماره یک:"))
        self.label_4.setText(_translate("IWindow", "آی پی دستگاه شماره چهار:"))
        self.label_5.setText(_translate("IWindow", "آی پی دستگاه شماره دو:"))
        self.label_6.setText(_translate("IWindow", "آی پی دستگاه شماره پنج:"))
        self.label_7.setText(_translate("IWindow", "آی پی دستگاه شماره سه:"))
        self.ok_ip_button.setText(_translate("IWindow", "تایید"))
        self.cancel_ip_button.setText(_translate("IWindow", "انصراف"))
        self.label_8.setText(_translate("IWindow", "*  صفر های سمت چپ هر بخش از آی پی وارد نشود"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IWindow = QtWidgets.QMainWindow()
    ui = Ui_IWindow()
    ui.setupUi(IWindow)
    IWindow.show()
    sys.exit(app.exec_())

