# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_report.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RWindow(object):
    def setupUi(self, RWindow):
        RWindow.setObjectName("RWindow")
        RWindow.resize(570, 316)
        RWindow.setMinimumSize(QtCore.QSize(570, 316))
        RWindow.setMaximumSize(QtCore.QSize(570, 316))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("online.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(RWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(440, 110, 101, 31))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.header_old = QtWidgets.QLabel(self.centralwidget)
        self.header_old.setGeometry(QtCore.QRect(340, 10, 201, 41))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.header_old.setFont(font)
        self.header_old.setObjectName("header_old")
        self.ok_button = QtWidgets.QPushButton(self.centralwidget)
        self.ok_button.setGeometry(QtCore.QRect(20, 250, 93, 28))
        font = QtGui.QFont()
        font.setFamily("B Lotus")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ok_button.setFont(font)
        self.ok_button.setObjectName("ok_button")
        self.cancel_button = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_button.setGeometry(QtCore.QRect(120, 250, 93, 28))
        font = QtGui.QFont()
        font.setFamily("B Lotus")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_button.setFont(font)
        self.cancel_button.setObjectName("cancel_button")
        self.question_box = QtWidgets.QComboBox(self.centralwidget)
        self.question_box.setGeometry(QtCore.QRect(12, 140, 531, 31))
        font = QtGui.QFont()
        font.setFamily("B Zar")
        font.setPointSize(9)
        self.question_box.setFont(font)
        self.question_box.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.question_box.setObjectName("question_box")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(440, 60, 101, 31))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 60, 101, 31))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.startYear = QtWidgets.QComboBox(self.centralwidget)
        self.startYear.setGeometry(QtCore.QRect(290, 60, 73, 22))
        self.startYear.setObjectName("startYear")
        self.startMonth = QtWidgets.QComboBox(self.centralwidget)
        self.startMonth.setGeometry(QtCore.QRect(370, 60, 51, 22))
        self.startMonth.setObjectName("startMonth")
        self.startDay = QtWidgets.QComboBox(self.centralwidget)
        self.startDay.setGeometry(QtCore.QRect(430, 60, 51, 22))
        self.startDay.setObjectName("startDay")
        self.endMonth = QtWidgets.QComboBox(self.centralwidget)
        self.endMonth.setGeometry(QtCore.QRect(100, 60, 51, 22))
        self.endMonth.setObjectName("endMonth")
        self.endDay = QtWidgets.QComboBox(self.centralwidget)
        self.endDay.setGeometry(QtCore.QRect(160, 60, 51, 22))
        self.endDay.setObjectName("endDay")
        self.endYear = QtWidgets.QComboBox(self.centralwidget)
        self.endYear.setGeometry(QtCore.QRect(20, 60, 73, 22))
        self.endYear.setObjectName("endYear")
        self.savePathLine = QtWidgets.QLineEdit(self.centralwidget)
        self.savePathLine.setGeometry(QtCore.QRect(10, 210, 441, 31))
        self.savePathLine.setObjectName("savePathLine")
        self.savePathButton = QtWidgets.QPushButton(self.centralwidget)
        self.savePathButton.setGeometry(QtCore.QRect(460, 210, 93, 31))
        self.savePathButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.savePathButton.setObjectName("savePathButton")
        RWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(RWindow)
        self.statusbar.setObjectName("statusbar")
        RWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RWindow)
        QtCore.QMetaObject.connectSlotsByName(RWindow)

    def retranslateUi(self, RWindow):
        _translate = QtCore.QCoreApplication.translate
        RWindow.setWindowTitle(_translate("RWindow", "گزارش گیری"))
        self.label.setText(_translate("RWindow", "سوال:"))
        self.header_old.setText(_translate("RWindow", "گزارش گیری:"))
        self.ok_button.setText(_translate("RWindow", "تایید"))
        self.cancel_button.setText(_translate("RWindow", "انصراف"))
        self.label_2.setText(_translate("RWindow", "از تاریخ: "))
        self.label_3.setText(_translate("RWindow", "تا تاریخ:"))
        self.savePathButton.setText(_translate("RWindow", "مسیر ذخیره"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RWindow = QtWidgets.QMainWindow()
    ui = Ui_RWindow()
    ui.setupUi(RWindow)
    RWindow.show()
    sys.exit(app.exec_())

