# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_server_ip.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SIWindow(object):
    def setupUi(self, SIWindow):
        SIWindow.setObjectName("SIWindow")
        SIWindow.resize(385, 393)
        SIWindow.setMinimumSize(QtCore.QSize(385, 362))
        SIWindow.setMaximumSize(QtCore.QSize(99999, 110000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("online.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SIWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(SIWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.header_new = QtWidgets.QLabel(self.centralwidget)
        self.header_new.setGeometry(QtCore.QRect(40, 0, 341, 41))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.header_new.setFont(font)
        self.header_new.setObjectName("header_new")
        self.server_ip = QtWidgets.QLineEdit(self.centralwidget)
        self.server_ip.setGeometry(QtCore.QRect(20, 50, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.server_ip.setFont(font)
        self.server_ip.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.server_ip.setInputMask("")
        self.server_ip.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.server_ip.setObjectName("server_ip")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 50, 171, 31))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.server_port = QtWidgets.QLineEdit(self.centralwidget)
        self.server_port.setGeometry(QtCore.QRect(20, 100, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.server_port.setFont(font)
        self.server_port.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.server_port.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.server_port.setObjectName("server_port")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(200, 200, 171, 31))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.server_user = QtWidgets.QLineEdit(self.centralwidget)
        self.server_user.setGeometry(QtCore.QRect(20, 150, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.server_user.setFont(font)
        self.server_user.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.server_user.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.server_user.setObjectName("server_user")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(210, 100, 161, 31))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.server_pass = QtWidgets.QLineEdit(self.centralwidget)
        self.server_pass.setGeometry(QtCore.QRect(20, 200, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.server_pass.setFont(font)
        self.server_pass.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.server_pass.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.server_pass.setObjectName("server_pass")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(200, 250, 171, 31))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.server_db = QtWidgets.QLineEdit(self.centralwidget)
        self.server_db.setGeometry(QtCore.QRect(20, 250, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.server_db.setFont(font)
        self.server_db.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.server_db.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.server_db.setObjectName("server_db")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(200, 150, 171, 31))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.ok_ip_button = QtWidgets.QPushButton(self.centralwidget)
        self.ok_ip_button.setGeometry(QtCore.QRect(100, 300, 93, 28))
        font = QtGui.QFont()
        font.setFamily("B Lotus")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ok_ip_button.setFont(font)
        self.ok_ip_button.setObjectName("ok_ip_button")
        self.cancel_ip_button = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_ip_button.setGeometry(QtCore.QRect(200, 300, 93, 28))
        font = QtGui.QFont()
        font.setFamily("B Lotus")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_ip_button.setFont(font)
        self.cancel_ip_button.setObjectName("cancel_ip_button")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 340, 331, 31))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        SIWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SIWindow)
        self.statusbar.setObjectName("statusbar")
        SIWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SIWindow)
        QtCore.QMetaObject.connectSlotsByName(SIWindow)

    def retranslateUi(self, SIWindow):
        _translate = QtCore.QCoreApplication.translate
        SIWindow.setWindowTitle(_translate("SIWindow", "افزودن نظرسنجی جدید"))
        self.header_new.setText(_translate("SIWindow", "مشخصات سرور دیتابیس مورد نظر را وارد نمایید:"))
        self.label_3.setText(_translate("SIWindow", "آی پی سرور"))
        self.label_4.setText(_translate("SIWindow", "رمز عبور سرور"))
        self.label_5.setText(_translate("SIWindow", "پورت سرور"))
        self.label_6.setText(_translate("SIWindow", "نام دیتابیس"))
        self.label_7.setText(_translate("SIWindow", "نام کاربری سرور"))
        self.ok_ip_button.setText(_translate("SIWindow", "تایید"))
        self.cancel_ip_button.setText(_translate("SIWindow", "انصراف"))
        self.label_8.setText(_translate("SIWindow", "*  صفر های سمت چپ از آی پی وارد نشود"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SIWindow = QtWidgets.QMainWindow()
    ui = Ui_SIWindow()
    ui.setupUi(SIWindow)
    SIWindow.show()
    sys.exit(app.exec_())

